version: "3.7"
services:
  nginxrtmp:
    image: ghcr.io/npetersendk/docker-nginx-rtmp:latest
    container_name: nginxrtmp
    ports:
      - "8000:80" #default nginx port
      - "1935:1935" #default RTMP port
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
      - ./stat.xsl:/var/www/html/stat.xsl:ro